version: '2'

services:
  frappe:
    image: pipech/erpnext-docker-debian:mas-py3-latest
    ports:
      - "8000:8000" #webserver_port
      - "9000:9000" #socketio_port
      - "6787:6787" #file_watcher_port
    volumes:
      # persisting data
      - ./data/bench/apps:/home/frappe/bench/apps
      # config
      - ./conf/frappe-docker-conf/init.sh:/home/frappe/bench/init.sh
      - ./conf/frappe-docker-conf/init.sql:/home/frappe/bench/init.sql
    stdin_open: true
    tty: true
    command: tail -f /dev/null

  mariadb:
    build: ./image/mariadb/.
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=mysql
    volumes:
      # persisting data
      - mariadb-data-volumes:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mariadb-data-volumes: